#image: node:latest
#
## Pick zero or more services to be used on all builds.
## Only needed when using a docker container to run your tests in.
## Check out: https://docs.gitlab.com/ee/ci/services/index.html
##services:
##  - mysql:latest
##  - redis:latest
##  - postgres:latest
#
## This folder is cached between builds
## https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/
build:
    script:
       - $dir = "release_${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}"
       - yarn
       - yarn run build:prod
       - yarn run build:dev
       - New-Item -Path $dir -ItemType Directory
       - Copy-Item -Path "dist_production" -Destination $dir -Recurse
       - Copy-Item -Path "dist_development" -Destination $dir -Recurse
    artifacts:
      paths:
        - release_${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}
      expire_in: 1 month

